CREATE TABLE HANGHOA
(
	[MAHH] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [TENHH] NVARCHAR(50) NULL, 
    [NGAYNHAPHANG] DATETIME NULL, 
    [GIABAN] NVARCHAR(50) NULL, 
    [MAMH] NVARCHAR(50) NULL, 
    [MAQG] NVARCHAR(50) NULL
)
